package com.eps.module.api.epsone.asset_tag_code.constant;

public class AssetTagCodeErrorMessages {
    public static final String GENERATOR_NOT_FOUND_ID = "Asset tag code generator not found with id: ";
    public static final String GENERATOR_EXISTS = "Asset tag code generator already exists for this category-vendor-bank combination";
    public static final String ASSET_CATEGORY_NOT_FOUND_ID = "Asset category not found with id: ";
    public static final String VENDOR_NOT_FOUND_ID = "Vendor not found with id: ";
    public static final String BANK_NOT_FOUND_ID = "Bank not found with id: ";
    public static final String CANNOT_DELETE_GENERATOR_USED = "Cannot delete asset tag code generator. %d asset(s) are using tags generated by this pattern (prefix: %s).";
    
    private AssetTagCodeErrorMessages() {}
}
